@startuml
actor User

participant "WebSocketBroker" as Broker
participant "PetManagerService" as Service

User -> Broker : HTTP request to connect WebSocket
Broker --> User : connected

User -> Broker : Subscribe to topic/petId

loop data stream
    Service -> Broker : send data to topic/petId
    Broker --> User : data
end
@enduml
