package com.mypetserver.mypetserver.repository;

import com.mypetserver.mypetserver.entities.Owner;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.query.Param;

/**
 * This interface describes the owner repository (table) as well as methods (queries) to said repository (table).
 * Some methods (queries) may be auto generated by Spring Data JPA.
 */
public interface OwnerRepository extends JpaRepository<Owner, String> {
    Owner findOwnerByUsername(@Param("username") String username);

    Owner findOwnerByEmail(@Param("email") String email);
}
